project_id = "rbdzinajiyswzdeoenil"

[functions.invite-user]
verify_jwt = false

[functions.check-heartbeat]
verify_jwt = false

[functions.station-control]
verify_jwt = false

[functions.generate-receipt]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
